### ISSUE TITLE
When running, it gives this error, how can I solve it?

### ISSUE THREAD

**Issue by nanosystem2022** [ytrevor81/TradingView-Binance-Telegram-Bot#10]
public]$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    bot = MainBot() #Handles all telegram communication
  File "/home/valibarg/topsms/public/bot.py", line 24, in __init__
    self.chat_ids = self.db.chat_ids()
  File "/home/valibarg/topsms/public/db_functions.py", line 29, in chat_ids
    found_users = self.c.execute("SELECT chat_id FROM user_info WHERE allow=1")
sqlite3.OperationalError: no such column: allow
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/valibarg/virtualenv/topsms/3.8/lib/python3.8/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

**Comment by Xspacezero** [comment]
I am facing this problem as well. Anyone know the solution?
