### ISSUE TITLE
terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by shamilcm007** [ytrevor81/TradingView-Binance-Telegram-Bot#5]
`$ flask run
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 128-523-810
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/extbot.py", line 221, in get_updates
    updates = super().get_updates(
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 129, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 2815, in get_updates
    self._post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 294, in _post
    return self.request.post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 356, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
`

How do I handle this error ?

**Comment by shamilcm007** [comment]
Any ideas

**Comment by virtueistheonlygood** [comment]
same issue

  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/ext/updater.py", line 601, in polling_action_cb
    allowed_updates=allowed_updates,
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/ext/extbot.py", line 228, in get_updates
    api_kwargs=api_kwargs,
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/bot.py", line 2865, in get_updates
    api_kwargs=api_kwargs,
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/utils/request.py", line 361, in post
    **urlopen_kwargs,
  File "/home/tfx/TradingView-Binance-Telegram-Bot/bot/lib/python3.7/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.

**Comment by sleyeborg** [comment]
how is this issue closed? you cant even run the introductory "hello world" sample code provided by telegram.js.org without this error popping up. it pops up when i try and use telegraf also. shouldnt this issue still be opened? the question was not answered.
