### ISSUE TITLE
Sqlite Database error open

### ISSUE THREAD

**Issue by Yoken0S** [ytrevor81/TradingView-Binance-Telegram-Bot#6]
Hi,

After al lot of problem I managed to install the bot but when I run it with WSGI it tells me that it can't open db.sqlite.
And when I removed it for let him create a new one it didn't work either

`[Wed Nov 10 18:16:19.588856 2021] [wsgi:error] [pid 5273] [] mod_wsgi (pid=5273): Failed to exec Python script file '/var/www/Trade/app.py'.
[Wed Nov 10 18:16:19.588990 2021] [wsgi:error] [pid 5273] [] mod_wsgi (pid=5273): Exception occurred processing WSGI script '/var/www/Trade/app.py'.
[Wed Nov 10 18:16:19.589521 2021] [wsgi:error] [pid 5273] [] Traceback (most recent call last):
[Wed Nov 10 18:16:19.589568 2021] [wsgi:error] [pid 5273] []   File "/var/www/Trade/app.py", line 13, in <module>
[Wed Nov 10 18:16:19.589574 2021] [wsgi:error] [pid 5273] []     bot = MainBot() #Handles all telegram communication
[Wed Nov 10 18:16:19.589580 2021] [wsgi:error] [pid 5273] []   File "/var/www/Trade/bot.py", line 22, in __init__
[Wed Nov 10 18:16:19.589584 2021] [wsgi:error] [pid 5273] []     self.initial_chat_id_check() #checks if chat_id is already in the DB
[Wed Nov 10 18:16:19.589590 2021] [wsgi:error] [pid 5273] []   File "/var/www/Trade/bot.py", line 29, in initial_chat_id_check
[Wed Nov 10 18:16:19.589605 2021] [wsgi:error] [pid 5273] []     DB = Database()
[Wed Nov 10 18:16:19.589611 2021] [wsgi:error] [pid 5273] []   File "/var/www/Trade/db_functions.py", line 10, in __init__
[Wed Nov 10 18:16:19.589614 2021] [wsgi:error] [pid 5273] []     self.conn = sqlite3.connect('/var/www/html/Trade/db.sqlite')
[Wed Nov 10 18:16:19.589630 2021] [wsgi:error] [pid 5273] [] sqlite3.OperationalError: unable to open database file`

**Comment by Yoken0S** [comment]
It is working great with Flask run so I think it is a path or right issue but I already give ownership to www-data and set chmod 777 to be sure but still don't work

**Comment by Yoken0S** [comment]
Ok,

Solution was to use absolute path like I did but I wrote it wrong

`self.conn = sqlite3.connect('/var/www/html/Trade/db.sqlite')`
